---
roles:
  - name: chriswayg.msmtp-mailer
    src: https://github.com/chriswayg/ansible-msmtp-mailer
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker
  - name: geerlingguy.pip
    src: https://github.com/geerlingguy/ansible-role-pip

collections:
  - name: community.general.docker_container
  - name: community.general
  - name: community.crypto
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
