---
- name: Create the config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/freshrss"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Make sure the Fresh RSS container is created and running
  register: freshrss_result
  community.general.docker_container:
    name: "freshrss"
    image: "lscr.io/linuxserver:{{ freshrss_version }}"
    pull: yes
    state: "started"
    volumes:
        - "{{ docker_dir }}/data:/config"
    ports:
        - "5432:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.6
    restart_policy: unless-stopped
